name: "Hello Actions"
description: "Greeings (part of Hello Github Actions)"
author: "GrantRVD@github.com"

inputs:
        MY_NAME:
                description: "Who to greet"
                required: true
                default: "World"

runs:
        using: "docker"
        image: "Dockerfile"

branding:
        icon: "mic"
        color: "purple"
